# Generated by Django 4.2.5 on 2023-10-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
