# Generated by Django 4.2.5 on 2023-10-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0002_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pass",
        ),
    ]
